---
name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: I need a way to …
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to see? Be specific.
      placeholder: Add a flag … / create a script …
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches and why they’re not ideal
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, prior art, screenshots
