---
name: ShellCheck

'on':
  pull_request:
    paths:
      - '**/*.sh'
      - '**/.bashrc'
      - '**/.bash_aliases'
      - '**/.zshrc'
      - '**/.profile'
  push:
    branches: [main]
    paths:
      - '**/*.sh'
      - '**/.bashrc'
      - '**/.bash_aliases'
      - '**/.zshrc'
      - '**/.profile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: error
          check_together: true
          path: .
